version: '3.8'

services:
  frontend:
    image: ayush272002/chat-app:frontend
    environment:
      - NEXT_PUBLIC_WS_BASE_URL=ws://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    image: ayush272002/chat-app:backend
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data: